# Welcome to Jekyll!

# Site settings
title: Paul Schaefer
tagline: designer & developer extraordinaire
email: paul@o2dca.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paulmakesthe.net" # the base hostname & protocol for your site, e.g. http://example.com
github: "https://github.com/pschfr/paulmakesthe.net"
analytics: "UA-76037357-1"

# Build settings
markdown: kramdown

# Changes links to articles/title.html
permalink: /:categories/:title/

# Obviously compresses the Sass output.
sass:
  style: compressed

# The HTML is compressed via _layouts/compress.html
# See: http://jch.penibelst.de/

# Additional plugins
plugins:
  - hawkins
  - jekyll-feed
  - jekyll-sitemap
