# Welcome to Jekyll!

# Site settings
title: Paul Schaefer
tagline: designer & developer extraordinaire
email: paul@o2dca.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paulmakesthe.net" # the base hostname & protocol for your site, e.g. http://example.com
github: "https://github.com/pschfr/paulmakesthe.net"

# jekyll-seo-tag stuff
twitter:
  username: pschfr
webmaster_verifications:
  google: 6oE0AWXPQEiL1noMkdqnjPuj7L8ZcEWeNtGROTbBmrg
  bing: CFF8D2634124B04EDC4FD8E13B0988A3

jekyll_analytics:
  GoogleAnalytics:
    id: UA-76037357-1

# Reset permalinks
permalink: none

# Build settings
markdown: kramdown

# Changes links to articles/title.html
permalink: /:categories/:title/

# Obviously compresses the Sass output.
sass:
  style: compressed

# The HTML is compressed via _layouts/compress.html
# See: http://jch.penibelst.de/

# Additional plugins
plugins:
  - hawkins
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-analytics
